# Generated by Django 6.0.3 on 2026-04-09 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0002_alter_cabana_options_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenCabana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='cabanas/')),
                ('cabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='cabanas.cabana')),
            ],
        ),
    ]
